# Generated by Django 3.1 on 2021-12-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variaton_value',
            new_name='variation_value',
        ),
    ]
