# Generated by Django 3.1 on 2022-01-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220112_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='prodct',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_preice',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
